// NES Emulator for MakeCode Arcade
// Entry point — the emulator logic is in nes-emulator.ts
// ROM data is loaded from rom-data.ts (generated by the converter)
//
// Quick-start:
// 1. Convert your ROM: python3 nes-rom-converter/convert.py game.nes rom-data.ts
// 2. Open this folder in MakeCode Arcade editor (https://arcade.makecode.com)
// 3. Flash to hardware or run in simulator
//
// Controller mapping:
// Arcade A → NES A
// Arcade B → NES B
// Arcade A+B together → NES Start
// Arcade D-pad → NES D-pad
