// ============================================================
// NES Emulator for MakeCode Arcade
// Complete single-file implementation
// Supports: Mapper 0 (NROM) + Mapper 1 (MMC1/SxROM)
// Target games: Donkey Kong, Pac-Man, Super Mario Bros, etc.
// ============================================================

// === NES 6502 CPU State ===
let cpuA: number = 0;      // Accumulator
let cpuX: number = 0;      // X index
let cpuY: number = 0;      // Y index
let cpuSP: number = 0xFD;  // Stack pointer
let cpuPC: number = 0;     // Program counter
let cpuC: number = 0;      // Carry flag
let cpuZ: number = 0;      // Zero flag
let cpuI: number = 1;      // Interrupt disable
let cpuD: number = 0;      // Decimal mode
let cpuV: number = 0;      // Overflow flag
let cpuN: number = 0;      // Negative flag
let cpuCycles: number = 0;
let nmiRequested: boolean = false;

// === PPU State ===
let ppuCtrl: number = 0;
let ppuMask: number = 0;
let ppuStatus: number = 0;
let ppuOamAddr: number = 0;
let ppuV: number = 0;       // Current VRAM address
let ppuT: number = 0;       // Temp VRAM address
let ppuFineX: number = 0;
let ppuAddrLatch: boolean = false;
let ppuDataBuf: number = 0;

// === VRAM, OAM, Palette ===
let ppuVram: number[] = [];
let ppuOam: number[] = [];
let ppuPalette: number[] = [];
let ppuChrData: number[] = [];
let ppuMirroring: number = 0;
let ppuFrameBuf: number[] = [];

// === Bus State ===
let busCpuRam: number[] = [];
let busPrgRom: number[] = [];
let busChrData: number[] = [];
let busMapper: number = 0;
let busMirroring: number = 0;
let busPrgSize: number = 0;
let busChrSize: number = 0;
let busHasChrRom: boolean = false;
let busSram: number[] = [];

// === MMC1 State ===
let mmc1Shift: number = 0x10;
let mmc1Control: number = 0x1C;
let mmc1ChrBank0: number = 0;
let mmc1ChrBank1: number = 0;
let mmc1PrgBank: number = 0;

// === Controller State ===
let ctrlState: number = 0;
let ctrlStrobe: number = 0;
let ctrlReadIndex: number = 0;
let ctrlReadState: number = 0;

// === Screen ===
let screenImage: Image = null;
let emuRunning: boolean = false;

// ============================================================
// NES palette to MakeCode Arcade 16-color mapping
// ============================================================
// NES 64-color → MakeCode Arcade Color enum mapping
// Generated by rom-converter/palette-gen.py (Euclidean closest-color)
// Arcade Color enum: 1=White, 2=Red, 3=Pink, 4=Orange, 5=Yellow,
//   6=Teal, 7=Green, 8=Blue, 9=LightBlue, 0xA=Purple, 0xB=LightPurple,
//   0xC=DarkPurple, 0xD=Tan, 0xE=Brown(dark navy), 0xF=Black
const COLOR_MAP: number[] = [
 0xC, 0xE, 0xE, 0xE, 0xA, 0xA, 0xA, 0xF, 0xF, 0xF, 0xF, 0xF, 0xE, 0xF, 0xF, 0xF,
 0xB, 0x8, 0x8, 0x9, 0x9, 0xA, 0xA, 0xD, 0xC, 0x7, 0x7, 0x7, 0x7, 0xF, 0xF, 0xF,
 0x1, 0x8, 0x8, 0x9, 0x9, 0x3, 0x3, 0xD, 0xD, 0xD, 0x6, 0x6, 0x7, 0xE, 0xF, 0xF,
 0x1, 0xB, 0xB, 0xB, 0xB, 0xB, 0x3, 0x3, 0x5, 0x5, 0x5, 0x5, 0xB, 0x9, 0xF, 0xF
];

// ============================================================
// INITIALIZATION
// ============================================================
function nesInit(): void {
    // CPU
    cpuA = 0; cpuX = 0; cpuY = 0; cpuSP = 0xFD;
    cpuC = 0; cpuZ = 0; cpuI = 1; cpuD = 0; cpuV = 0; cpuN = 0;
    cpuCycles = 0; nmiRequested = false;

    // PPU
    ppuCtrl = 0; ppuMask = 0; ppuStatus = 0;
    ppuOamAddr = 0; ppuV = 0; ppuT = 0; ppuFineX = 0;
    ppuAddrLatch = false; ppuDataBuf = 0;
    ppuVram = []; ppuOam = []; ppuPalette = []; ppuFrameBuf = [];
    for (let i = 0; i < 2048; i++) ppuVram.push(0);
    for (let i = 0; i < 256; i++) ppuOam.push(0);
    for (let i = 0; i < 32; i++) ppuPalette.push(0);
    for (let i = 0; i < 256 * 240; i++) ppuFrameBuf.push(0);

    // Bus
    busCpuRam = []; busSram = [];
    for (let i = 0; i < 2048; i++) busCpuRam.push(0);
    for (let i = 0; i < 8192; i++) busSram.push(0);

    // MMC1
    mmc1Shift = 0x10; mmc1Control = 0x1C;
    mmc1ChrBank0 = 0; mmc1ChrBank1 = 0; mmc1PrgBank = 0;

    // Controller
    ctrlState = 0; ctrlStrobe = 0;
    ctrlReadIndex = 0; ctrlReadState = 0;

    // Load ROM data (from rom-data.ts, generated by converter)
    romInit();
    busPrgRom = romPrgData;
    busChrData = romChrData;
    busMapper = romMapper;
    busMirroring = romMirroring;
    busPrgSize = romPrgSize;
    busChrSize = romChrSize;
    busHasChrRom = romHasChrRom;
    ppuMirroring = busMirroring;

    if (!busHasChrRom) {
        ppuChrData = [];
        for (let i = 0; i < 8192; i++) ppuChrData.push(0);
    } else {
        ppuChrData = busChrData;
    }

    // CPU reset vector
    cpuPC = busRead(0xFFFC) | (busRead(0xFFFD) << 8);
    cpuCycles = 7;

 screenImage = image.create(160, 120);
 screenImage.fill(0);
 emuRunning = true;
}

// ============================================================
// BUS - CPU Read/Write
// ============================================================
function busRead(addr: number): number {
    addr &= 0xFFFF;
    if (addr < 0x2000) return busCpuRam[addr & 0x07FF];
    if (addr < 0x4000) return ppuReadReg(addr & 7);
    if (addr == 0x4016) return ctrlRead();
    if (addr >= 0x6000 && addr < 0x8000) {
        if (busMapper == 1) return busSram[addr & 0x1FFF];
        return 0;
    }
    if (addr >= 0x8000) return prgRead(addr);
    return 0;
}

function busWrite(addr: number, val: number): void {
    addr &= 0xFFFF; val &= 0xFF;
    if (addr < 0x2000) { busCpuRam[addr & 0x07FF] = val; return; }
    if (addr < 0x4000) { ppuWriteReg(addr & 7, val); return; }
    if (addr == 0x4014) {
        // OAM DMA
        let page = val << 8;
        for (let i = 0; i < 256; i++) ppuOam[(ppuOamAddr + i) & 0xFF] = busRead(page + i);
        return;
    }
    if (addr == 0x4016) { ctrlWriteStrobe(val); return; }
    if (addr >= 0x6000 && addr < 0x8000) {
        if (busMapper == 1) busSram[addr & 0x1FFF] = val;
        return;
    }
    if (addr >= 0x8000) { mapperWrite(addr, val); }
}

function prgRead(addr: number): number {
    addr &= 0xFFFF;
    if (busMapper == 0) {
        if (busPrgSize == 1) return busPrgRom[addr & 0x3FFF];
        return busPrgRom[addr & 0x7FFF];
    } else if (busMapper == 1) {
        let mode = (mmc1Control >> 2) & 3;
        let prgAddr: number;
        if (mode == 3 || mode == 2) {
            if (mode == 3) {
                // 32KB switch
                let bank = mmc1PrgBank & 0xFE;
                prgAddr = bank * 16384 + (addr - 0x8000);
            } else {
                // Fix first, switch second
                if (addr < 0xC000) prgAddr = addr - 0x8000;
                else prgAddr = mmc1PrgBank * 16384 + (addr - 0xC000);
            }
        } else if (mode == 1) {
            // Switch first, fix last
            if (addr < 0xC000) prgAddr = mmc1PrgBank * 16384 + (addr - 0x8000);
            else prgAddr = (busPrgRom.length - 16384) + (addr - 0xC000);
        } else {
            if (addr < 0xC000) prgAddr = addr - 0x8000;
            else prgAddr = mmc1PrgBank * 16384 + (addr - 0xC000);
        }
        return busPrgRom[prgAddr % busPrgRom.length];
    }
    return 0;
}

function mapperWrite(addr: number, val: number): void {
    if (busMapper == 0) return;
    if (busMapper == 1) mmc1Write(addr, val);
}

function mmc1Write(addr: number, val: number): void {
    if (val & 0x80) {
        mmc1Shift = 0x10;
        mmc1Control |= 0x0C;
        return;
    }
    let complete = (mmc1Shift & 1) != 0;
    mmc1Shift = (mmc1Shift >> 1) | ((val & 1) << 4);
    if (complete) {
        let reg = (addr >> 13) & 3;
        let data = mmc1Shift & 0x1F;
        if (reg == 0) {
            mmc1Control = data;
            let m = data & 3;
            if (m == 2) ppuMirroring = 0;
            else if (m == 3) ppuMirroring = 1;
        } else if (reg == 1) {
            mmc1ChrBank0 = data;
            mmc1UpdateChr();
        } else if (reg == 2) {
            mmc1ChrBank1 = data;
            mmc1UpdateChr();
        } else if (reg == 3) {
            mmc1PrgBank = data & 0x0F;
        }
        mmc1Shift = 0x10;
    }
}

function mmc1UpdateChr(): void {
    let chrMode = (mmc1Control >> 4) & 1;
    if (chrMode == 0) {
        let bank = mmc1ChrBank0 & 0xFE;
        for (let i = 0; i < 8192; i++) ppuChrData[i] = busChrData[(bank * 4096 + i) % busChrData.length];
    } else {
        for (let i = 0; i < 4096; i++) {
            ppuChrData[i] = busChrData[(mmc1ChrBank0 * 4096 + i) % busChrData.length];
            ppuChrData[4096 + i] = busChrData[(mmc1ChrBank1 * 4096 + i) % busChrData.length];
        }
    }
}

// ============================================================
// PPU
// ============================================================
function ppuMirrorAddr(addr: number): number {
    addr = (addr - 0x2000) & 0x0FFF;
    let table = addr >> 10;
    let offset = addr & 0x3FF;
    if (ppuMirroring == 0) {
        if (table == 1) table = 0;
        if (table == 3) table = 2;
    } else {
        if (table == 2) table = 0;
        if (table == 3) table = 1;
    }
    return (table << 10) | offset;
}

function ppuVramRead(addr: number): number {
    addr &= 0x3FFF;
    if (addr < 0x2000) {
        if (addr < ppuChrData.length) return ppuChrData[addr];
        return 0;
    } else if (addr < 0x3F00) {
        return ppuVram[ppuMirrorAddr(addr)];
    } else {
        return ppuPaletteRead(addr);
    }
}

function ppuVramWrite(addr: number, val: number): void {
    addr &= 0x3FFF; val &= 0xFF;
    if (addr < 0x2000) {
        if (ppuChrData.length > 0) ppuChrData[addr] = val;
    } else if (addr < 0x3F00) {
        ppuVram[ppuMirrorAddr(addr)] = val;
    } else {
        ppuPaletteWrite(addr, val);
    }
}

function ppuPaletteRead(addr: number): number {
    addr &= 0x1F;
    if ((addr & 0x13) == 0x10) addr ^= 0x10;
    return ppuPalette[addr];
}

function ppuPaletteWrite(addr: number, val: number): void {
    addr &= 0x1F;
    if ((addr & 0x13) == 0x10) addr ^= 0x10;
    ppuPalette[addr] = val & 0x3F;
}

function ppuReadReg(reg: number): number {
    if (reg == 2) {
        let r = (ppuStatus & 0xE0) | (ppuDataBuf & 0x1F);
        ppuStatus &= 0x7F;
        ppuAddrLatch = false;
        return r;
    }
    if (reg == 4) return ppuOam[ppuOamAddr];
    if (reg == 7) {
        let data = ppuDataBuf;
        ppuDataBuf = ppuVramRead(ppuV);
        if ((ppuV & 0x3FFF) >= 0x3F00) { data = ppuDataBuf; ppuDataBuf = ppuVramRead(ppuV); }
        ppuV = ((ppuV & 0x3FFF) + ((ppuCtrl & 0x04) ? 32 : 1)) & 0x7FFF;
        return data;
    }
    return 0;
}

function ppuWriteReg(reg: number, val: number): void {
    val &= 0xFF;
    if (reg == 0) {
        ppuCtrl = val;
        ppuT = (ppuT & 0x73FF) | ((val & 0x03) << 10);
        if ((val & 0x80) && (ppuStatus & 0x80)) nmiRequested = true;
    } else if (reg == 1) {
        ppuMask = val;
    } else if (reg == 3) {
        ppuOamAddr = val;
    } else if (reg == 4) {
        ppuOam[ppuOamAddr] = val;
        ppuOamAddr = (ppuOamAddr + 1) & 0xFF;
    } else if (reg == 5) {
        if (!ppuAddrLatch) {
            ppuT = (ppuT & 0x7FE0) | ((val >> 3) & 0x1F);
            ppuFineX = val & 0x07;
            ppuAddrLatch = true;
        } else {
            ppuT = (ppuT & 0x0C1F) | (((val >> 3) & 0x1F) << 5) | ((val & 0x07) << 12);
            ppuAddrLatch = false;
        }
    } else if (reg == 6) {
        if (!ppuAddrLatch) {
            ppuT = (ppuT & 0x00FF) | ((val & 0x3F) << 8);
            ppuAddrLatch = true;
        } else {
            ppuT = (ppuT & 0xFF00) | val;
            ppuV = ppuT;
            ppuAddrLatch = false;
        }
    } else if (reg == 7) {
        ppuVramWrite(ppuV, val);
        ppuV = ((ppuV & 0x3FFF) + ((ppuCtrl & 0x04) ? 32 : 1)) & 0x7FFF;
    }
}

// ============================================================
// PPU RENDERING
// ============================================================
function ppuRenderFrame(): void {
    if (!(ppuMask & 0x18)) {
        let bg = ppuPaletteRead(0);
        for (let i = 0; i < ppuFrameBuf.length; i++) ppuFrameBuf[i] = bg;
        ppuStatus |= 0x80;
        if (ppuCtrl & 0x80) nmiRequested = true;
        return;
    }

    for (let y = 0; y < 240; y++) {
        let rowOff = y * 256;
        if (ppuMask & 0x08) renderBg(y, rowOff);
        else { let bg = ppuPaletteRead(0); for (let x = 0; x < 256; x++) ppuFrameBuf[rowOff + x] = bg; }
        if (ppuMask & 0x10) renderSprites(y, rowOff);
    }

    ppuStatus |= 0x80;
    if (ppuCtrl & 0x80) nmiRequested = true;
}

function renderBg(y: number, rowOff: number): void {
 // Scroll components from ppuV (set during VBlank by $2005/$2006)
 let scrollX = ((ppuV & 0x1F) << 3) + ppuFineX;
 let scrollY = ((ppuV >> 12) & 7) + (((ppuV >> 5) & 0x1F) << 3);
 let baseNtY = (ppuV >> 11) & 1;
 let baseNtX = (ppuV >> 10) & 1;

 for (let x = 0; x < 256; x++) {
 let pixelX = scrollX + x;
 let pixelY = scrollY + y;

 let ntX = baseNtX ^ ((pixelX >> 8) & 1);
 let ntY = baseNtY ^ ((pixelY >> 8) & 1);
 let ntAddr = 0x2000 + ((ntY ? 2 : 0) + (ntX ? 1 : 0)) * 0x400;

 let tileX = (pixelX >> 3) & 0x1F;
 let tileY = (pixelY >> 3) & 0x1F;

 let ntByte = ppuVramRead(ntAddr + tileY * 32 + tileX);

 let atAddr = ntAddr + 0x03C0;
 let atByte = ppuVramRead(atAddr + ((tileY >> 2) * 8) + (tileX >> 2));
 let shift = ((tileY & 2) * 4) + ((tileX & 2) * 2);
 let atVal = (atByte >> shift) & 3;

 let chrAddr = ((ppuCtrl & 0x10) ? 0x1000 : 0x0000) + ntByte * 16 + (pixelY & 7);
 let lo = ppuVramRead(chrAddr);
 let hi = ppuVramRead(chrAddr + 8);

 let bit = 7 - (pixelX & 7);
 let pixel = ((hi >> bit) & 1) << 1 | ((lo >> bit) & 1);

 if (pixel == 0) ppuFrameBuf[rowOff + x] = ppuPaletteRead(0);
 else ppuFrameBuf[rowOff + x] = ppuPaletteRead(0x3F00 + (atVal << 2) + pixel);
 }
}

function renderSprites(y: number, rowOff: number): void {
    let spr8x16 = (ppuCtrl & 0x20) != 0;
    for (let i = 63; i >= 0; i--) {
        let base = i * 4;
        let sY = ppuOam[base] + 1;
        let sTile = ppuOam[base + 1];
        let sAttr = ppuOam[base + 2];
        let sX = ppuOam[base + 3];
        let sH = spr8x16 ? 16 : 8;

        let dy = y - sY;
        if (dy < 0 || dy >= sH) continue;
        if (sAttr & 0x80) dy = sH - 1 - dy;

        let tileAddr: number;
        if (spr8x16) {
            tileAddr = (sTile & 1) * 0x1000 + (sTile & 0xFE) * 16 + dy;
        } else {
            tileAddr = ((ppuCtrl & 0x08) ? 0x1000 : 0x0000) + sTile * 16 + dy;
        }

        let lo = ppuVramRead(tileAddr);
        let hi = ppuVramRead(tileAddr + 8);
        let flipH = (sAttr & 0x40) != 0;
        let palOff = 0x10 + ((sAttr & 0x03) << 2);
        let behind = (sAttr & 0x20) != 0;

        for (let px = 0; px < 8; px++) {
            let bit = flipH ? px : (7 - px);
            let pixel = ((hi >> bit) & 1) << 1 | ((lo >> bit) & 1);
            if (pixel == 0) continue;

            let sx = sX + px;
            if (sx >= 256) break;
            if (sx < 8 && !(ppuMask & 0x02)) continue;

            if (behind && ppuFrameBuf[rowOff + sx] != ppuPaletteRead(0)) continue;

            ppuFrameBuf[rowOff + sx] = ppuPaletteRead(palOff + pixel);
        }
    }
}

// ============================================================
// CONTROLLER INPUT
// ============================================================
function ctrlPoll(): void {
 let s = 0;
 // Arcade A → NES A (bit 0)
 if (controller.A.isPressed()) s |= 0x01;
 // Arcade B → NES B (bit 1)
 if (controller.B.isPressed()) s |= 0x02;
 // Arcade A+B together → NES Start (bit 3) — workaround since controller.menu doesn't exist
 if (controller.A.isPressed() && controller.B.isPressed()) s |= 0x08;
 // D-pad → NES D-pad (bits 4-7)
 if (controller.up.isPressed()) s |= 0x10;
 if (controller.down.isPressed()) s |= 0x20;
 if (controller.left.isPressed()) s |= 0x40;
 if (controller.right.isPressed()) s |= 0x80;
 ctrlState = s;
}

function ctrlWriteStrobe(val: number): void {
    val &= 1;
    if (ctrlStrobe && !val) { ctrlReadState = ctrlState; ctrlReadIndex = 0; }
    ctrlStrobe = val;
}

function ctrlRead(): number {
    if (ctrlStrobe) { ctrlReadState = ctrlState; ctrlReadIndex = 0; }
    let r = (ctrlReadState >> ctrlReadIndex) & 1;
    ctrlReadIndex = (ctrlReadIndex + 1) & 7;
    return r;
}

// ============================================================
// 6502 CPU - ALL 56 OFFICIAL OPCODES
// ============================================================
function cpuSetZN(val: number): void {
    cpuZ = (val & 0xFF) == 0 ? 1 : 0;
    cpuN = (val & 0x80) != 0 ? 1 : 0;
}

function cpuPush(val: number): void {
    busWrite(0x100 | cpuSP, val & 0xFF);
    cpuSP = (cpuSP - 1) & 0xFF;
}

function cpuPull(): number {
    cpuSP = (cpuSP + 1) & 0xFF;
    return busRead(0x100 | cpuSP);
}

function cpuPush16(val: number): void { cpuPush((val >> 8) & 0xFF); cpuPush(val & 0xFF); }
function cpuPull16(): number { let lo = cpuPull(); let hi = cpuPull(); return (hi << 8) | lo; }

function cpuGetP(): number {
    return (cpuN << 7) | (cpuV << 6) | 1 | (1 << 4) | (cpuD << 3) | (cpuI << 2) | (cpuZ << 1) | cpuC;
}

function cpuSetP(val: number): void {
    cpuC = (val) & 1; cpuZ = (val >> 1) & 1; cpuI = (val >> 2) & 1;
    cpuD = (val >> 3) & 1; cpuV = (val >> 6) & 1; cpuN = (val >> 7) & 1;
}

// Helper: branch with signed offset
function doBranch(cond: boolean): void {
    let offset = busRead(cpuPC); cpuPC = (cpuPC + 1) & 0xFFFF;
    if (cond) { cpuPC = (cpuPC + (offset < 128 ? offset : offset - 256)) & 0xFFFF; cpuCycles += 2; }
    cpuCycles++;
}

// Helper: ADC
function doADC(val: number): void {
    let sum = cpuA + val + cpuC;
    cpuC = sum > 0xFF ? 1 : 0;
    cpuV = (~(cpuA ^ val) & (cpuA ^ sum) & 0x80) ? 1 : 0;
    cpuA = sum & 0xFF; cpuSetZN(cpuA);
}

// Helper: SBC
function doSBC(val: number): void {
    let diff = cpuA - val - (1 - cpuC);
    cpuC = diff >= 0 ? 1 : 0;
    cpuV = ((cpuA ^ val) & (cpuA ^ diff) & 0x80) ? 1 : 0;
    cpuA = diff & 0xFF; cpuSetZN(cpuA);
}

// Helper: CMP
function doCMP(reg: number, val: number): void {
    cpuC = reg >= val ? 1 : 0;
    cpuSetZN((reg - val) & 0xFF);
}

function cpuStep(): number {
    // Handle NMI
    if (nmiRequested) {
        nmiRequested = false;
        cpuPush16(cpuPC);
        cpuPush(cpuGetP() & 0xEF);
        cpuI = 1;
        cpuPC = busRead(0xFFFA) | (busRead(0xFFFB) << 8);
        cpuCycles += 7;
        return 7;
    }

    let op = busRead(cpuPC);
    cpuPC = (cpuPC + 1) & 0xFFFF;
    let startCyc = cpuCycles;
    let addr = 0;
    let tmp = 0;
    let val = 0;

    switch (op) {
        // ---- LDA ----
        case 0xA9: cpuA = busRead(cpuPC); cpuPC++; cpuSetZN(cpuA); cpuCycles++; break;
        case 0xA5: cpuA = busRead(busRead(cpuPC)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 2; break;
        case 0xB5: cpuA = busRead((busRead(cpuPC) + cpuX) & 0xFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0xAD: cpuA = busRead(busRead(cpuPC) | (busRead(cpuPC + 1) << 8)); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0xBD: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); val = busRead((addr + cpuX) & 0xFFFF); cpuPC += 2; cpuA = val; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr + cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0xB9: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); val = busRead((addr + cpuY) & 0xFFFF); cpuPC += 2; cpuA = val; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr + cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0xA1: addr = (busRead(cpuPC) + cpuX) & 0xFF; cpuA = busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 5; break;
        case 0xB1: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); cpuA = busRead((addr + cpuY) & 0xFFFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr + cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- LDX ----
        case 0xA2: cpuX = busRead(cpuPC); cpuPC++; cpuSetZN(cpuX); cpuCycles++; break;
        case 0xA6: cpuX = busRead(busRead(cpuPC)); cpuPC++; cpuSetZN(cpuX); cpuCycles += 2; break;
        case 0xB6: cpuX = busRead((busRead(cpuPC) + cpuY) & 0xFF); cpuPC++; cpuSetZN(cpuX); cpuCycles += 3; break;
        case 0xAE: cpuX = busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8)); cpuPC += 2; cpuSetZN(cpuX); cpuCycles += 3; break;
        case 0xBE: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuX = busRead((addr + cpuY) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuX); cpuCycles += ((addr & 0xFF00) != ((addr + cpuY) & 0xFF00)) ? 4 : 3; break;

        // ---- LDY ----
        case 0xA0: cpuY = busRead(cpuPC); cpuPC++; cpuSetZN(cpuY); cpuCycles++; break;
        case 0xA4: cpuY = busRead(busRead(cpuPC)); cpuPC++; cpuSetZN(cpuY); cpuCycles += 2; break;
        case 0xB4: cpuY = busRead((busRead(cpuPC) + cpuX) & 0xFF); cpuPC++; cpuSetZN(cpuY); cpuCycles += 3; break;
        case 0xAC: cpuY = busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8)); cpuPC += 2; cpuSetZN(cpuY); cpuCycles += 3; break;
        case 0xBC: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuY = busRead((addr + cpuX) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuY); cpuCycles += ((addr & 0xFF00) != ((addr + cpuX) & 0xFF00)) ? 4 : 3; break;

        // ---- STA ----
        case 0x85: busWrite(busRead(cpuPC), cpuA); cpuPC++; cpuCycles += 2; break;
        case 0x95: busWrite((busRead(cpuPC) + cpuX) & 0xFF, cpuA); cpuPC++; cpuCycles += 3; break;
        case 0x8D: busWrite(busRead(cpuPC) | (busRead(cpuPC+1) << 8), cpuA); cpuPC += 2; cpuCycles += 3; break;
        case 0x9D: busWrite(((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF, cpuA); cpuPC += 2; cpuCycles += 4; break;
        case 0x99: busWrite(((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuY) & 0xFFFF, cpuA); cpuPC += 2; cpuCycles += 4; break;
        case 0x81: addr = (busRead(cpuPC) + cpuX) & 0xFF; busWrite(busRead(addr) | (busRead((addr+1) & 0xFF) << 8), cpuA); cpuPC++; cpuCycles += 5; break;
        case 0x91: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)) + cpuY; busWrite(addr & 0xFFFF, cpuA); cpuPC++; cpuCycles += 5; break;

        // ---- STX ----
        case 0x86: busWrite(busRead(cpuPC), cpuX); cpuPC++; cpuCycles += 2; break;
        case 0x96: busWrite((busRead(cpuPC) + cpuY) & 0xFF, cpuX); cpuPC++; cpuCycles += 3; break;
        case 0x8E: busWrite(busRead(cpuPC) | (busRead(cpuPC+1) << 8), cpuX); cpuPC += 2; cpuCycles += 3; break;

        // ---- STY ----
        case 0x84: busWrite(busRead(cpuPC), cpuY); cpuPC++; cpuCycles += 2; break;
        case 0x94: busWrite((busRead(cpuPC) + cpuX) & 0xFF, cpuY); cpuPC++; cpuCycles += 3; break;
        case 0x8C: busWrite(busRead(cpuPC) | (busRead(cpuPC+1) << 8), cpuY); cpuPC += 2; cpuCycles += 3; break;

        // ---- Transfers ----
        case 0xAA: cpuX = cpuA; cpuSetZN(cpuX); cpuCycles++; break;
        case 0xA8: cpuY = cpuA; cpuSetZN(cpuY); cpuCycles++; break;
        case 0x8A: cpuA = cpuX; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x98: cpuA = cpuY; cpuSetZN(cpuA); cpuCycles++; break;
        case 0xBA: cpuX = cpuSP; cpuSetZN(cpuX); cpuCycles++; break;
        case 0x9A: cpuSP = cpuX; cpuCycles++; break;

        // ---- ADC ----
        case 0x69: doADC(busRead(cpuPC)); cpuPC++; cpuCycles++; break;
        case 0x65: doADC(busRead(busRead(cpuPC))); cpuPC++; cpuCycles += 2; break;
        case 0x75: doADC(busRead((busRead(cpuPC) + cpuX) & 0xFF)); cpuPC++; cpuCycles += 3; break;
        case 0x6D: doADC(busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8))); cpuPC += 2; cpuCycles += 3; break;
        case 0x7D: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); doADC(busRead((addr+cpuX) & 0xFFFF)); cpuPC += 2; cpuCycles += ((addr & 0xFF00) != ((addr+cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0x79: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); doADC(busRead((addr+cpuY) & 0xFFFF)); cpuPC += 2; cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0x61: addr = (busRead(cpuPC) + cpuX) & 0xFF; doADC(busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8))); cpuPC++; cpuCycles += 5; break;
        case 0x71: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); doADC(busRead((addr+cpuY) & 0xFFFF)); cpuPC++; cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- SBC ----
        case 0xE9: doSBC(busRead(cpuPC)); cpuPC++; cpuCycles++; break;
        case 0xE5: doSBC(busRead(busRead(cpuPC))); cpuPC++; cpuCycles += 2; break;
        case 0xF5: doSBC(busRead((busRead(cpuPC) + cpuX) & 0xFF)); cpuPC++; cpuCycles += 3; break;
        case 0xED: doSBC(busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8))); cpuPC += 2; cpuCycles += 3; break;
        case 0xFD: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); doSBC(busRead((addr+cpuX) & 0xFFFF)); cpuPC += 2; cpuCycles += ((addr & 0xFF00) != ((addr+cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0xF9: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); doSBC(busRead((addr+cpuY) & 0xFFFF)); cpuPC += 2; cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0xE1: addr = (busRead(cpuPC) + cpuX) & 0xFF; doSBC(busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8))); cpuPC++; cpuCycles += 5; break;
        case 0xF1: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); doSBC(busRead((addr+cpuY) & 0xFFFF)); cpuPC++; cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- AND ----
        case 0x29: cpuA &= busRead(cpuPC); cpuPC++; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x25: cpuA &= busRead(busRead(cpuPC)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 2; break;
        case 0x35: cpuA &= busRead((busRead(cpuPC)+cpuX) & 0xFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x2D: cpuA &= busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8)); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x3D: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuA &= busRead((addr+cpuX) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0x39: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuA &= busRead((addr+cpuY) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0x21: addr = (busRead(cpuPC)+cpuX) & 0xFF; cpuA &= busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 5; break;
        case 0x31: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); cpuA &= busRead((addr+cpuY) & 0xFFFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- ORA ----
        case 0x09: cpuA |= busRead(cpuPC); cpuPC++; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x05: cpuA |= busRead(busRead(cpuPC)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 2; break;
        case 0x15: cpuA |= busRead((busRead(cpuPC)+cpuX) & 0xFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x0D: cpuA |= busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8)); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x1D: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuA |= busRead((addr+cpuX) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0x19: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuA |= busRead((addr+cpuY) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0x01: addr = (busRead(cpuPC)+cpuX) & 0xFF; cpuA |= busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 5; break;
        case 0x11: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); cpuA |= busRead((addr+cpuY) & 0xFFFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- EOR ----
        case 0x49: cpuA ^= busRead(cpuPC); cpuPC++; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x45: cpuA ^= busRead(busRead(cpuPC)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 2; break;
        case 0x55: cpuA ^= busRead((busRead(cpuPC)+cpuX) & 0xFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x4D: cpuA ^= busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8)); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x5D: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuA ^= busRead((addr+cpuX) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0x59: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuA ^= busRead((addr+cpuY) & 0xFFFF); cpuPC += 2; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0x41: addr = (busRead(cpuPC)+cpuX) & 0xFF; cpuA ^= busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8)); cpuPC++; cpuSetZN(cpuA); cpuCycles += 5; break;
        case 0x51: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); cpuA ^= busRead((addr+cpuY) & 0xFFFF); cpuPC++; cpuSetZN(cpuA); cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- CMP ----
        case 0xC9: doCMP(cpuA, busRead(cpuPC)); cpuPC++; cpuCycles++; break;
        case 0xC5: doCMP(cpuA, busRead(busRead(cpuPC))); cpuPC++; cpuCycles += 2; break;
        case 0xD5: doCMP(cpuA, busRead((busRead(cpuPC)+cpuX) & 0xFF)); cpuPC++; cpuCycles += 3; break;
        case 0xCD: doCMP(cpuA, busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8))); cpuPC += 2; cpuCycles += 3; break;
        case 0xDD: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); doCMP(cpuA, busRead((addr+cpuX) & 0xFFFF)); cpuPC += 2; cpuCycles += ((addr & 0xFF00) != ((addr+cpuX) & 0xFF00)) ? 4 : 3; break;
        case 0xD9: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); doCMP(cpuA, busRead((addr+cpuY) & 0xFFFF)); cpuPC += 2; cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 4 : 3; break;
        case 0xC1: addr = (busRead(cpuPC)+cpuX) & 0xFF; doCMP(cpuA, busRead(busRead(addr) | (busRead((addr+1) & 0xFF) << 8))); cpuPC++; cpuCycles += 5; break;
        case 0xD1: tmp = busRead(cpuPC); addr = (busRead(tmp) | (busRead((tmp+1) & 0xFF) << 8)); doCMP(cpuA, busRead((addr+cpuY) & 0xFFFF)); cpuPC++; cpuCycles += ((addr & 0xFF00) != ((addr+cpuY) & 0xFF00)) ? 5 : 4; break;

        // ---- CPX ----
        case 0xE0: doCMP(cpuX, busRead(cpuPC)); cpuPC++; cpuCycles++; break;
        case 0xE4: doCMP(cpuX, busRead(busRead(cpuPC))); cpuPC++; cpuCycles += 2; break;
        case 0xEC: doCMP(cpuX, busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8))); cpuPC += 2; cpuCycles += 3; break;

        // ---- CPY ----
        case 0xC0: doCMP(cpuY, busRead(cpuPC)); cpuPC++; cpuCycles++; break;
        case 0xC4: doCMP(cpuY, busRead(busRead(cpuPC))); cpuPC++; cpuCycles += 2; break;
        case 0xCC: doCMP(cpuY, busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8))); cpuPC += 2; cpuCycles += 3; break;

        // ---- INC ----
        case 0xE6: addr = busRead(cpuPC); tmp = (busRead(addr)+1)&0xFF; busWrite(addr, tmp); cpuPC++; cpuSetZN(tmp); cpuCycles += 4; break;
        case 0xF6: addr = (busRead(cpuPC)+cpuX) & 0xFF; tmp = (busRead(addr)+1)&0xFF; busWrite(addr, tmp); cpuPC++; cpuSetZN(tmp); cpuCycles += 5; break;
        case 0xEE: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); tmp = (busRead(addr)+1)&0xFF; busWrite(addr, tmp); cpuPC += 2; cpuSetZN(tmp); cpuCycles += 5; break;
        case 0xFE: addr = ((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF; tmp = (busRead(addr)+1)&0xFF; busWrite(addr, tmp); cpuPC += 2; cpuSetZN(tmp); cpuCycles += 6; break;

        // ---- DEC ----
        case 0xC6: addr = busRead(cpuPC); tmp = (busRead(addr)-1)&0xFF; busWrite(addr, tmp); cpuPC++; cpuSetZN(tmp); cpuCycles += 4; break;
        case 0xD6: addr = (busRead(cpuPC)+cpuX) & 0xFF; tmp = (busRead(addr)-1)&0xFF; busWrite(addr, tmp); cpuPC++; cpuSetZN(tmp); cpuCycles += 5; break;
        case 0xCE: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); tmp = (busRead(addr)-1)&0xFF; busWrite(addr, tmp); cpuPC += 2; cpuSetZN(tmp); cpuCycles += 5; break;
        case 0xDE: addr = ((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF; tmp = (busRead(addr)-1)&0xFF; busWrite(addr, tmp); cpuPC += 2; cpuSetZN(tmp); cpuCycles += 6; break;

        // ---- INX/INY/DEX/DEY ----
        case 0xE8: cpuX = (cpuX+1) & 0xFF; cpuSetZN(cpuX); cpuCycles++; break;
        case 0xC8: cpuY = (cpuY+1) & 0xFF; cpuSetZN(cpuY); cpuCycles++; break;
        case 0xCA: cpuX = (cpuX-1) & 0xFF; cpuSetZN(cpuX); cpuCycles++; break;
        case 0x88: cpuY = (cpuY-1) & 0xFF; cpuSetZN(cpuY); cpuCycles++; break;

        // ---- ASL ----
        case 0x0A: cpuC = (cpuA >> 7) & 1; cpuA = (cpuA << 1) & 0xFF; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x06: addr = busRead(cpuPC); val = busRead(addr); cpuC = (val >> 7) & 1; busWrite(addr, (val << 1) & 0xFF); cpuSetZN((val << 1) & 0xFF); cpuPC++; cpuCycles += 4; break;
        case 0x16: addr = (busRead(cpuPC)+cpuX) & 0xFF; val = busRead(addr); cpuC = (val >> 7) & 1; busWrite(addr, (val << 1) & 0xFF); cpuSetZN((val << 1) & 0xFF); cpuPC++; cpuCycles += 5; break;
        case 0x0E: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); val = busRead(addr); cpuC = (val >> 7) & 1; busWrite(addr, (val << 1) & 0xFF); cpuSetZN((val << 1) & 0xFF); cpuPC += 2; cpuCycles += 5; break;
        case 0x1E: addr = ((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF; val = busRead(addr); cpuC = (val >> 7) & 1; busWrite(addr, (val << 1) & 0xFF); cpuSetZN((val << 1) & 0xFF); cpuPC += 2; cpuCycles += 6; break;

        // ---- LSR ----
        case 0x4A: cpuC = cpuA & 1; cpuA = (cpuA >> 1) & 0xFF; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x46: addr = busRead(cpuPC); val = busRead(addr); cpuC = val & 1; busWrite(addr, (val >> 1) & 0xFF); cpuSetZN((val >> 1) & 0xFF); cpuPC++; cpuCycles += 4; break;
        case 0x56: addr = (busRead(cpuPC)+cpuX) & 0xFF; val = busRead(addr); cpuC = val & 1; busWrite(addr, (val >> 1) & 0xFF); cpuSetZN((val >> 1) & 0xFF); cpuPC++; cpuCycles += 5; break;
        case 0x4E: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); val = busRead(addr); cpuC = val & 1; busWrite(addr, (val >> 1) & 0xFF); cpuSetZN((val >> 1) & 0xFF); cpuPC += 2; cpuCycles += 5; break;
        case 0x5E: addr = ((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF; val = busRead(addr); cpuC = val & 1; busWrite(addr, (val >> 1) & 0xFF); cpuSetZN((val >> 1) & 0xFF); cpuPC += 2; cpuCycles += 6; break;

        // ---- ROL ----
        case 0x2A: tmp = cpuA; cpuA = ((cpuA << 1) | cpuC) & 0xFF; cpuC = (tmp >> 7) & 1; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x26: addr = busRead(cpuPC); tmp = busRead(addr); busWrite(addr, ((tmp << 1) | cpuC) & 0xFF); cpuC = (tmp >> 7) & 1; cpuSetZN(((tmp << 1) | cpuC) & 0xFF); cpuPC++; cpuCycles += 4; break;
        case 0x36: addr = (busRead(cpuPC)+cpuX) & 0xFF; tmp = busRead(addr); busWrite(addr, ((tmp << 1) | cpuC) & 0xFF); cpuC = (tmp >> 7) & 1; cpuSetZN(((tmp << 1) | cpuC) & 0xFF); cpuPC++; cpuCycles += 5; break;
        case 0x2E: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); tmp = busRead(addr); busWrite(addr, ((tmp << 1) | cpuC) & 0xFF); cpuC = (tmp >> 7) & 1; cpuSetZN(((tmp << 1) | cpuC) & 0xFF); cpuPC += 2; cpuCycles += 5; break;
        case 0x3E: addr = ((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF; tmp = busRead(addr); busWrite(addr, ((tmp << 1) | cpuC) & 0xFF); cpuC = (tmp >> 7) & 1; cpuSetZN(((tmp << 1) | cpuC) & 0xFF); cpuPC += 2; cpuCycles += 6; break;

        // ---- ROR ----
        case 0x6A: tmp = cpuA; cpuA = (cpuA >> 1) | (cpuC << 7); cpuC = tmp & 1; cpuSetZN(cpuA); cpuCycles++; break;
        case 0x66: addr = busRead(cpuPC); tmp = busRead(addr); busWrite(addr, (tmp >> 1) | (cpuC << 7)); cpuC = tmp & 1; cpuSetZN((tmp >> 1) | (cpuC << 7)); cpuPC++; cpuCycles += 4; break;
        case 0x76: addr = (busRead(cpuPC)+cpuX) & 0xFF; tmp = busRead(addr); busWrite(addr, (tmp >> 1) | (cpuC << 7)); cpuC = tmp & 1; cpuSetZN((tmp >> 1) | (cpuC << 7)); cpuPC++; cpuCycles += 5; break;
        case 0x6E: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); tmp = busRead(addr); busWrite(addr, (tmp >> 1) | (cpuC << 7)); cpuC = tmp & 1; cpuSetZN((tmp >> 1) | (cpuC << 7)); cpuPC += 2; cpuCycles += 5; break;
        case 0x7E: addr = ((busRead(cpuPC) | (busRead(cpuPC+1) << 8)) + cpuX) & 0xFFFF; tmp = busRead(addr); busWrite(addr, (tmp >> 1) | (cpuC << 7)); cpuC = tmp & 1; cpuSetZN((tmp >> 1) | (cpuC << 7)); cpuPC += 2; cpuCycles += 6; break;

        // ---- BIT ----
        case 0x24: tmp = busRead(busRead(cpuPC)); cpuPC++; cpuZ = (cpuA & tmp) == 0 ? 1 : 0; cpuV = (tmp >> 6) & 1; cpuN = (tmp >> 7) & 1; cpuCycles += 2; break;
        case 0x2C: tmp = busRead(busRead(cpuPC) | (busRead(cpuPC+1) << 8)); cpuPC += 2; cpuZ = (cpuA & tmp) == 0 ? 1 : 0; cpuV = (tmp >> 6) & 1; cpuN = (tmp >> 7) & 1; cpuCycles += 3; break;

        // ---- Branches ----
        case 0x10: doBranch(!cpuN); break;  // BPL
        case 0x30: doBranch(!!cpuN); break;  // BMI
        case 0x50: doBranch(!cpuV); break;  // BVC
        case 0x70: doBranch(!!cpuV); break;  // BVS
        case 0x90: doBranch(!cpuC); break;  // BCC
        case 0xB0: doBranch(!!cpuC); break;  // BCS
        case 0xD0: doBranch(!cpuZ); break;  // BNE
        case 0xF0: doBranch(!!cpuZ); break;  // BEQ

        // ---- JMP ----
        case 0x4C: cpuPC = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuCycles += 2; break;
        case 0x6C: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuPC = busRead(addr) | (busRead((addr & 0xFF00) | ((addr+1) & 0xFF)) << 8); cpuCycles += 4; break;

        // ---- JSR ----
        case 0x20: addr = busRead(cpuPC) | (busRead(cpuPC+1) << 8); cpuPush16(cpuPC + 1); cpuPC = addr; cpuCycles += 5; break;

        // ---- RTS ----
        case 0x60: cpuPC = (cpuPull16() + 1) & 0xFFFF; cpuCycles += 5; break;

        // ---- RTI ----
        case 0x40: cpuSetP(cpuPull()); cpuPC = cpuPull16(); cpuCycles += 5; break;

        // ---- BRK ----
        case 0x00: cpuPC++; cpuPush16(cpuPC); cpuPush(cpuGetP() | 0x10); cpuI = 1; cpuPC = busRead(0xFFFE) | (busRead(0xFFFF) << 8); cpuCycles += 6; break;

        // ---- Stack ----
        case 0x48: cpuPush(cpuA); cpuCycles += 2; break;
        case 0x68: cpuA = cpuPull(); cpuSetZN(cpuA); cpuCycles += 3; break;
        case 0x08: cpuPush(cpuGetP() | 0x30); cpuCycles += 2; break;
        case 0x28: cpuSetP(cpuPull() & 0xEF); cpuCycles += 3; break;

        // ---- Flags ----
        case 0x18: cpuC = 0; cpuCycles++; break;
        case 0x38: cpuC = 1; cpuCycles++; break;
        case 0x58: cpuI = 0; cpuCycles++; break;
        case 0x78: cpuI = 1; cpuCycles++; break;
        case 0xD8: cpuD = 0; cpuCycles++; break;
        case 0xF8: cpuD = 1; cpuCycles++; break;
        case 0xB8: cpuV = 0; cpuCycles++; break;

        // ---- NOP ----
        case 0xEA: cpuCycles++; break;

        default: cpuCycles++; break;  // Unimplemented as NOP
    }

    cpuPC &= 0xFFFF;
    return cpuCycles - startCyc;
}

// ============================================================
// FRAME EXECUTION + SCREEN RENDERING
// ============================================================
function nesRunFrame(): void {
 if (!emuRunning) return;
 ctrlPoll();

 // Execute CPU for one frame's worth of cycles
 // NMI fires partway through (at scanline 241), but for simplicity
 // we render first, then run CPU which will see the NMI
 ppuRenderFrame();

 // Now run CPU — it will process the VBlank NMI from ppuRenderFrame
 let target = cpuCycles + 29780;
 while (cpuCycles < target) cpuStep();

 // After frame: clear VBlank flag for next frame
 ppuStatus &= 0x7F;

 // Draw to screen
 renderToScreen();
}

function renderToScreen(): void {
 // NES 256x240 → Arcade 160x120
 // We center the NES frame: 160 cols from NES cols 48..207, 120 rows from NES rows 0..119
 // (skipping 48px left/right gives a centered 160-wide crop of the 256-wide NES)
 for (let y = 0; y < 120; y++) {
 let nesY = y * 2; // Sample every other row for vertical scaling
 if (nesY >= 240) break;
 let rowOff = nesY * 256;
 for (let x = 0; x < 160; x++) {
 let nesX = x + 48; // Center crop: NES columns 48-207 → Arcade columns 0-159
 let nesColor = ppuFrameBuf[rowOff + nesX];
 screenImage.setPixel(x, y, COLOR_MAP[nesColor & 0x3F]);
 }
 }
}

// ============================================================
// MAKECODE ARCADE ENTRY POINTS
// ============================================================
// Initialize NES on startup
nesInit();
scene.setBackgroundImage(screenImage);

// Run one NES frame per Arcade update tick
game.onUpdate(function () {
 if (emuRunning) nesRunFrame();
});
